version: '3.8'

secrets:
  Admin:
    external: true
  SoccerWebsiteDb:
    external: true
  SoccerWebsitePwd:
    external: true

services:
  soccerwebapp:
    image: soccerwebapp_container
    ports:
      - "3000:3000"
    depends_on:
      - soccerwebapp_db
    secrets:
      - Admin
      - SoccerWebsiteDb
      - SoccerWebsitePwd

  soccerwebapp_db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - soccerwebapp_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/SoccerWebsiteDb
    secrets:
      - SoccerWebsiteDb

volumes:
  soccerwebapp_volume:
